info:
  contact:
    email: 这里写联系人邮箱
    name: 这里写联系人名字
  description: 这里写描述信息
  termsOfService: http://swagger.io/terms/
  title: 这里写标题
  version: "1.0"
paths:
  /user/login:
    get:
      consumes:
      - application/json
      description: 这里写描述 get users
      parameters:
      - description: Id
        in: query
        name: Id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 摘要 比如获取用户列表
      tags:
      - ops 标签 比如同类功能使用同一个标签
swagger: "2.0"
