info:
  contact:
    name: ekreke
  description: myTodoList's api docs
  title: myTodolist
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: user login
      parameters:
      - description: Id
        in: query
        name: Id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: userlogin
      tags:
      - User
swagger: "2.0"
