basePath: /api/v1
definitions:
  model.Users:
    properties:
      apartment_id:
        type: integer
      avatar:
        type: string
      bio:
        type: string
      id:
        type: integer
      link:
        type: string
      password:
        type: string
      projects_id:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    name: ekreke
  description: myTodoList's api docs
  title: myTodolist
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 创建镜像迁移任务
      parameters:
      - description: 请示参数data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Users'
      produces:
      - application/json
      responses: {}
      summary: 创建镜像迁移任务
      tags:
      - User
swagger: "2.0"
